package com.nyahonk.currencyconverter

enum class CurrenciesMap(val currency: String) {
    RUB("RUB"),
    USD("USD"),
    EUR("EUR"),
    CAD("CAD"),
    HKD("HKD"),
    ISK("ISK"),
    PHP("PHP"),
    DKK("DKK"),
    HUF("HUF"),
    CZK("CZK"),
    GBP("GBP"),
    RON("RON"),
    SEK("SEK"),
    IDR("IDR"),
    INR("INR"),
    BRL("BRL"),
    HRK("HRK"),
    JPY("JPY"),
    THB("THB"),
    CHF("CHF"),
    MYR("MYR"),
    BGN("BGN"),
    TRY("TRY"),
    CNY("CNY"),
    NOK("NOK"),
    NZD("NZD"),
    ZAR("ZAR"),
    MXN("MXN"),
    SGD("SGD"),
    AUD("AUD"),
    ILS("ILS"),
    KRW("KRW"),
    PLN("PLN")
}